### PR TITLE
Bugfix/mygames command

### LINKED ISSUE #45: Players not in DB cannot use !mygames commands
All commands including !mygames as listing, addition, deletion of game are working as it is just for players in the database.

So implementation of addition of a new player into the database when not found is needed.

### PR DESCRIPTION
**Pull request by Teg3z**
Database couldn't handle commands which tried to find users name in the Players collection, which were all commands with prefix **!mygames**.

I implemented a checks in this PR for users existence in the DB and if there is no documents with users name, then it is created.

I also removed **nick** property for Players in the collection since it was useless as we handle all users by their DC ID (property **name**).

Functionality was tested and is working. Closes #45

### CODE REVIEW

**Comment by R4tmax** [comment]
Take note that this PR is incorrectly forked, you have duplicit commits for hash [0f43725](https://github.com/Teg3z/Wheel-of-Luck/pull/44/commits/0f43725b9b62ddc006f7b03d6e1626ec09b52ab8) . 
This might cause merge conflict with #44 . (unsure whether github will autocorrect for same commit, used to have some issues with this back at my old job, but that was bitbucket)

**Comment by R4tmax** [comment]
You could cancel the first PR and finish all of the bugfixes on this branch. 
Not exactly clean execution but it gets the job done.

**Comment by Teg3z** [comment]
Ok so basically I have just learned rebasing. Its kinda complicated so in future I will not branch from unstable branches. But right now I will keep rebasing this branch until the #44 PR is merged and after that i will rebase this branch onto develop and everything will be ok, its just too complex like this, but im glad I tried it i guess, even tho it wasnt needed.

**Review by R4tmax — APPROVED** [review]
Mistakes with this are understandable, dw too much about it. 

You can see that GH tracks your commits as force push, this should be last resort only. 
Some people actually _preffer_ rebasing, so it depends I guess. 

My stance is that always branching from a stable branch is the best way how to prevent and mitigate conflicts. 
Recommend: https://nvie.com/posts/a-successful-git-branching-model/ as reading, used this at my work and in my bachelor thesis, good stuff. 

Otherwise, nice work!

**Pull request merged**
